# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.cache/wt [current_project]
set_property parent.project_path C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/zgnhz/Desktop/graduatedesign/dds
  c:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs
} [current_project]
set_property ip_output_repo c:/Users/zgnhz/Desktop/graduatedesign/dds/dds.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/zgnhz/Desktop/graduatedesign/dds/sin512.coe
add_files C:/Users/zgnhz/Desktop/graduatedesign/dds/sqw512.coe
add_files -quiet C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.runs/pll_synth_1/pll.dcp
set_property used_in_implementation false [get_files C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.runs/pll_synth_1/pll.dcp]
add_files -quiet C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.runs/sin_synth_1/sin.dcp
set_property used_in_implementation false [get_files C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.runs/sin_synth_1/sin.dcp]
add_files -quiet C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.runs/squ_synth_1/squ.dcp
set_property used_in_implementation false [get_files C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.runs/squ_synth_1/squ.dcp]
read_verilog -library xil_defaultlib C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/new/DDS.v
read_ip -quiet C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/pll/pll.xci
set_property used_in_implementation false [get_files -all c:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/pll/pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/pll/pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/pll/pll_late.xdc]
set_property used_in_implementation false [get_files -all c:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/pll/pll_ooc.xdc]

read_ip -quiet C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/sin/sin.xci
set_property used_in_implementation false [get_files -all c:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/sin/sin_ooc.xdc]

read_ip -quiet C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/squ/squ.xci
set_property used_in_implementation false [get_files -all c:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/squ/squ_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/constrs_1/imports/new/key.xdc
set_property used_in_implementation false [get_files C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/constrs_1/imports/new/key.xdc]

read_xdc C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/constrs_1/imports/new/an108_hdmi.xdc
set_property used_in_implementation false [get_files C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/constrs_1/imports/new/an108_hdmi.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top DDS -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DDS.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DDS_utilization_synth.rpt -pb DDS_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
