# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/sin/sin.xci
# IP: The module: 'sin' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/sin/sin_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sin'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/sin/sin.xci
# IP: The module: 'sin' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zgnhz/Desktop/graduatedesign/dds/dds.srcs/sources_1/ip/sin/sin_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sin'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
